-- MySQL Script generated by MySQL Workbench
-- Thu Dec 16 20:20:09 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema sakila_warehouse
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema sakila_warehouse
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `sakila_warehouse` ;
USE `sakila_warehouse` ;

-- -----------------------------------------------------
-- Table `sakila_warehouse`.`customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_warehouse`.`customer` (
  `customer_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT TRUE,
  `country` VARCHAR(45) NULL,
  `city` VARCHAR(45) NULL,
  `postal_code` VARCHAR(45) NULL,
  PRIMARY KEY (`customer_id`),
  INDEX `idx_last_name` (`last_name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers.Basic information about the customer like first and last name are stored in the table, including country, city, and postal code.';


-- -----------------------------------------------------
-- Table `sakila_warehouse`.`film`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_warehouse`.`film` (
  `film_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `length` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `replacement_cost` DECIMAL(5,2) NOT NULL DEFAULT 19.99,
  `category_name` VARCHAR(25) NULL,
  INDEX `idx_title` (`title` ASC) VISIBLE,
  PRIMARY KEY (`film_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila_warehouse`.`film_actor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_warehouse`.`film_actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL,
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`actor_id`, `film_id`),
  INDEX `idx_fk_film_id` (`film_id` ASC) VISIBLE,
  CONSTRAINT `fk_film_actor_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `sakila_warehouse`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila_warehouse`.`staff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_warehouse`.`staff` (
  `staff_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `store_id` TINYINT UNSIGNED NOT NULL,
  PRIMARY KEY (`staff_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila_warehouse`.`store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_warehouse`.`store` (
  `store_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manager_staff_id` TINYINT UNSIGNED NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`store_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `sakila_warehouse`.`fact`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `sakila_warehouse`.`fact` (
  `rental_id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `film_id` SMALLINT UNSIGNED NULL,
  `staff_id` TINYINT UNSIGNED NULL,
  `store_id` TINYINT UNSIGNED NULL,
  `rental_date` DATETIME NULL,
  `return_date` DATETIME NULL,
  `rental_days` TINYINT GENERATED ALWAYS AS (DATEDIFF(return_date,rental_date)) VIRTUAL,
  `rental_duration` TINYINT NULL,
  `penalty` TINYINT(1) GENERATED ALWAYS AS (IF(rental_days>rental_duration,TRUE,FALSE)) VIRTUAL,
  `amount` DECIMAL(5,2) NULL,
  `rental_rate` DECIMAL(5,2) NULL,
  `late_fee` DECIMAL(5,2) GENERATED ALWAYS AS (amount-rental_rate) VIRTUAL,
  PRIMARY KEY (`rental_id`),
  UNIQUE INDEX `rental_id_UNIQUE` (`rental_id` ASC) VISIBLE,
  INDEX `customer_id_idx` (`customer_id` ASC) VISIBLE,
  INDEX `staff_id_idx` (`staff_id` ASC) VISIBLE,
  INDEX `store_id_idx` (`store_id` ASC) VISIBLE,
  INDEX `film_id_idx` (`film_id` ASC) VISIBLE,
  CONSTRAINT `customer_id`
    FOREIGN KEY (`customer_id`)
    REFERENCES `sakila_warehouse`.`customer` (`customer_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `staff_id`
    FOREIGN KEY (`staff_id`)
    REFERENCES `sakila_warehouse`.`staff` (`staff_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `store_id`
    FOREIGN KEY (`store_id`)
    REFERENCES `sakila_warehouse`.`store` (`store_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `film_id`
    FOREIGN KEY (`film_id`)
    REFERENCES `sakila_warehouse`.`film` (`film_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
